swiftmailer:
    #delivery_addresses: ['skm.jeremy@gmail.com']
    transport: smtp
    auth_mode: login
    port: 465
    host: smtp.phpnet.org
    username: hello@hedee.co
    password: Bouya123
    encryption: ssl
    #url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' }
