#index:
#    path: /
#    controller: App\Controller\DefaultController::index


foire_aux_questions:
    path: /faq
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/faq.html.twig'


conditions:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/cgv.html.twig'

a_propos:
    path: /a-propos
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/a_propos/cgv.html.twig'