#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /deconnexion
    
foire_aux_questions:
    path: /faq
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/faq.html.twig'


conditions:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/cgv.html.twig'

a_propos:
    path: /qui-sommes-nous
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/a_propos.html.twig'

comment_ca_marche:
    path: /comment_ca_marche
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'utile/how.html.twig'  

#/contact:
#    path: /contact
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#    defaults:
#      template: 'utile/contact.html.twig'

test:
    path: /test
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'test.html.twig'
